version: '3'
services:
  python-api:
    build:
      context: app  # Docker context
      dockerfile: Dockerfile  # Path to your Dockerfile
    container_name: python-api
    ports:
      - "5000:5000"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 24.5m

  user-storage:
    build:
      context: user-storage
      dockerfile: Dockerfile.storage
    mem_limit: 200m  
    ports:
      - "5001:80"
    networks:
      - app-network

  book-storage:
    build:
      context: book-storage
      dockerfile: Dockerfile.storage
    mem_limit: 200m
    ports:
      - "5002:80"
    networks:
      - app-network

  rating-storage:
    build:
      context: rating-storage
      dockerfile: Dockerfile.storage
    mem_limit: 200m
    ports:
      - "5003:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge