version: '3'
services:
  your_app:
    build:
      context: .  # Docker context
      dockerfile: Dockerfile  # Path to your Dockerfile
    container_name: python-app
    volumes:
      - ./b-trees:/app/bin_files
    deploy:
      resources:
        limits:
          memory: 200M
